# Generated by Django 2.0.5 on 2018-08-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kategori_adi', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['id'],
            },
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name_plural': 'Gönderilerim'},
        ),
        migrations.AddField(
            model_name='post',
            name='kategori',
            field=models.ManyToManyField(to='posts.Category'),
        ),
    ]
