# Generated by Django 2.0.5 on 2018-08-11 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20180810_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='kategori',
            field=models.ManyToManyField(related_name='post', to='posts.Category'),
        ),
    ]
