# Generated by Django 2.0.5 on 2018-08-12 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20180812_1629'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Kategori', 'verbose_name_plural': 'Kategoriler'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['id'], 'verbose_name': 'Gönderi', 'verbose_name_plural': 'Gönderilerim'},
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='başıl giriniz.', max_length=120, verbose_name='Başlık'),
        ),
    ]
