# Generated by Django 2.0.5 on 2018-08-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20180812_1634'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-id'], 'verbose_name': 'Gönderi', 'verbose_name_plural': 'Gönderilerim'},
        ),
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='', verbose_name='Post Resim'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(help_text='başlık giriniz.', max_length=120, verbose_name='Başlık'),
        ),
    ]
