# Generated by Django 2.0.5 on 2018-08-26 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20180820_2307'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='selam', editable=False, max_length=122, unique=True, verbose_name='Slug Alani'),
            preserve_default=False,
        ),
    ]
