# Generated by Django 2.0.5 on 2018-09-16 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['tarih'], 'verbose_name': 'Yorumlar', 'verbose_name_plural': 'Yorumlar'},
        ),
        migrations.AddField(
            model_name='comment',
            name='icerik',
            field=models.TextField(default=2, max_length=1000, verbose_name='içerik'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment', to='posts.Post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='tarih',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='isim_soyisim',
            field=models.CharField(max_length=100, verbose_name='isim soyisim'),
        ),
    ]
