# Generated by Django 2.0.5 on 2018-09-24 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_auto_20180922_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-tarih'], 'verbose_name': 'Yorumlar', 'verbose_name_plural': 'Yorumlar'},
        ),
    ]
