# Generated by Django 2.0.5 on 2018-09-27 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_auto_20180924_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='etiket',
            field=models.CharField(blank=True, max_length=50, verbose_name='Etiketler'),
        ),
    ]
