# Generated by Django 2.0.5 on 2018-09-27 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0017_auto_20180927_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=20, verbose_name='Etiket')),
            ],
            options={
                'verbose_name': 'Etiket',
                'verbose_name_plural': 'Etiketler',
            },
        ),
        migrations.RemoveField(
            model_name='etiket',
            name='gonderi',
        ),
        migrations.DeleteModel(
            name='Etiket',
        ),
        migrations.AddField(
            model_name='post',
            name='etiket',
            field=models.ManyToManyField(related_name='post', to='posts.Tag', verbose_name='Etiketler'),
        ),
    ]
