# Generated by Django 2.0.5 on 2018-09-29 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0021_auto_20180927_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='resim',
            field=models.ImageField(default=3, upload_to='', verbose_name='Kullanıcı Resim'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(default=3, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Yazar'),
        ),
    ]
