# Generated by Django 2.0.5 on 2018-09-29 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0022_auto_20180929_1201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='resim',
        ),
    ]
