# Generated by Django 2.0.5 on 2018-09-29 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0023_remove_comment_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='counter',
            field=models.IntegerField(default=0, verbose_name='counter'),
        ),
    ]
