# Generated by Django 2.0.5 on 2018-10-02 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0029_post_is_favorite'),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteBlog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Favorilere Eklenen Gönderiler',
                'verbose_name_plural': 'Favorilere Eklenen Gönderiler',
            },
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_favorite',
        ),
        migrations.AddField(
            model_name='favoriteblog',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteBlog', to='posts.Post', verbose_name='Post'),
        ),
        migrations.AddField(
            model_name='favoriteblog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favoriteBlog', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
    ]
