# Generated by Django 2.0.5 on 2018-10-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0030_auto_20181002_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='isim',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Etiket'),
        ),
    ]
