# Generated by Django 2.0.5 on 2018-09-24 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import users.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefon', models.CharField(blank=True, max_length=11, verbose_name='Telefon Numarası')),
                ('cinsiyet', models.CharField(blank=True, default=3, max_length=1, verbose_name='Cinsiyet')),
                ('hakkinda', models.TextField(blank=True, max_length=500, verbose_name='Hakkimda')),
                ('dogumTarihi', models.DateField(blank=True, verbose_name='Doğum Tarihi')),
                ('profilPhoto', models.ImageField(upload_to=users.models.upload_to, verbose_name='Profil Fotoğrafı')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Kullanıcı Bilgileri',
            },
        ),
    ]
