# Generated by Django 2.0.5 on 2018-09-25 07:00

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='cinsiyet',
            field=models.CharField(blank=True, choices=[('E', 'Erkek'), ('K', 'Kadin'), ('O', 'Other')], default=3, max_length=1, verbose_name='Cinsiyet'),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='hakkinda',
            field=models.TextField(blank=True, max_length=500, verbose_name='Hakkımda'),
        ),
        migrations.AlterField(
            model_name='userprofil',
            name='profilPhoto',
            field=models.ImageField(default='static/img/userprofile.png', upload_to=users.models.upload_to, verbose_name='Profil Fotoğrafı'),
        ),
    ]
