# Generated by Django 2.0.5 on 2018-09-25 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180925_1004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofil',
            name='dogumTarihi',
            field=models.DateField(blank=True, null=True, verbose_name='Doğum Tarihi'),
        ),
    ]
