# Generated by Django 2.0.5 on 2018-09-25 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180925_1556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='hakkinda',
            new_name='hakkimda',
        ),
    ]
